name: Update Trailhead Stats

on:
  schedule:
    - cron: '*/5 * * * *' # Runs daily

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: nabondance/Trailhead-Stats@v2.0.0
        with:
          trailhead-username: 'SalesforceJohn'
          display-type: 'card'
          show-skill: 'hidden'
          show-certification: 'detail'
          show-superbadge: 'number'
          show-event-badge: 'number'
          show-stamp: 'number'

