name: Update Trailhead Stats

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily
  workflow_dispatch

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: nabondance/trailhead-stats@v2
        with:
          trailhead-username: 'SalesforceJohn'
          display-type: 'card'
